# Generated by Django 3.2.12 on 2022-03-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
